com.diffplug.spotless:spotless-plugin-gradle = 8.0.0
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.github.ben-manes.caffeine:caffeine = 3.2.3
com.google.auto.service:auto-service = 1.1.1
com.google.code.findbugs:* = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
com.google.guava:guava = 33.5.0-jre
com.google.guava:guava-testlib = 27.0.1-jre
com.google.testing.compile:compile-testing = 0.23.0
com.google.truth:truth = 1.4.5
com.palantir.sls.versions:sls-versions = 1.8.0
com.netflix.nebula:nebula-test = 10.0.0
junit:junit = 4.13.2
org.assertj:assertj-core = 3.27.6
org.derive4j:* = 1.1.1
org.functionaljava:functionaljava = 4.8
org.immutables:value = 2.11.6
org.junit.jupiter:* = 6.0.1
org.junit.vintage:* = 6.0.1
org.junit.platform:* = 6.0.1
org.slf4j:* = 2.0.17
com.fasterxml.jackson.*:* = 2.20.0
org.openjdk.jmh:* = 1.37
com.palantir.gradle.utils:* = 0.21.0
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.3.0
