apply plugin: 'java'

dependencies {
    api project(':palantir-java-format')

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter-migrationsupport'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
}

javaVersion {
    target = 21
    runtime = 21
}