apply plugin: 'distribution'
apply plugin: 'me.champeau.jmh'

dependencies {
    jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess'
    compileOnly 'org.openjdk.jmh:jmh-generator-annprocess'

    jmhImplementation 'org.assertj:assertj-core'
    jmhImplementation 'org.junit.jupiter:junit-jupiter'
    jmhImplementation 'org.openjdk.jmh:jmh-core'
    jmhImplementation 'org.openjdk.jmh:jmh-generator-annprocess'
}

tasks.named('processJmhResources', ProcessResources.class) {
    from(project(':palantir-java-format').tasks.named('fatJar')) {
        rename { 'palantir-java-format-all.jar' }
    }
    from(project(':palantir-java-format').tasks.named('nativeCompile')) {
        rename { 'palantir-java-format'}
    }
}

jmhCompileGeneratedClasses {
    options.errorprone.enabled = false
}
